name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - './**'
      
jobs:
  
    #Run unit tests
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    - name: 'Install dependencies'
      run: npm install
    - name: 'Run tests'
      run: npm run test
      
  # Run the linter to check for code style issues
  lint:
    name: 'Run linter'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npx standard -v
